### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by timstephens** [WiringPi/WiringPi-Python#10]
I'm seeing an issue where the setup.py script isn't finishing properly which means that the module isn't installed.

Here's the pertinent part of the output from the setup.py script:

```
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c WiringPi/devLib/piGlow.c -o build/temp.linux-armv6l-2.7/WiringPi/devLib/piGlow.o
WiringPi/devLib/piGlow.c:26:20: fatal error: sn3218.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import wiringpi2 as wiringpi
  File "/home/pi/WiringPi2-Python/wiringpi2.py", line 26, in <module>
    _wiringpi2 = swig_import_helper()
  File "/home/pi/WiringPi2-Python/wiringpi2.py", line 18, in swig_import_helper
    import _wiringpi2
ImportError: /usr/local/lib/python2.7/dist-packages/wiringpi2-1.0.10-py2.7-linux-armv6l.egg/_wiringpi2.so: undefined symbol: piGlowSetup
```

I've already installed the wiringpi2 tool and library. 

    gpio -v

returns

```
gpio version: 2.05
Copyright (c) 2012-2013 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

This Raspberry Pi is a revision 2 board.
```

So I don't think it's the same issue as #4.

**Comment by Gadgetoid** [comment]
The library *should* now build without WiringPi being built and installed, but I've not had the chance to test it properly. I need to apply everything I've learned about Python packaging over the last 3 years back to this neglected project!
